spring:
  datasource:
    url: jdbc:mysql://localhost:3306/expensetrackerDB?createDatabaseIfNotExist=true
    username: root
    password: Nimbus*8000
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl